RegisterNetEvent("plouffe_vangelico:sendConfig", Vr.LoadPlayer)
RegisterNetEvent("plouffe_vangelico:entry_grinder", Vr.OpenEntry)
RegisterNetEvent("plouffe_vangelico:unlock_office", Vr.OpenOffice)
RegisterNetEvent("plouffe_vangelico:hack_succes", Vr.HackSucces)
RegisterNetEvent("plouffe_vangelico:try_loot", Vr.TryLoot)